### ISSUE TITLE
[Question] .NET 8 support

### ISSUE THREAD

**Issue by tmaster-terrarian** [RonenNess/Iguina#1]
Does/will this library support .NET 8 projects?

**Comment by RonenNess** [comment]
Yeah maybe its time I move from 7.0 to 8.0.
Released 1.0.8 that switched to .net 8.0.

Should be available in couple of minutes here

[https://www.nuget.org/packages/Iguina/1.0.8](https://www.nuget.org/packages/Iguina/1.0.8)

Thanks!
