### ISSUE TITLE
Flickering (layout) frame delay on opening new elements

### ISSUE THREAD

**Issue by RudyTheDev** [RonenNess/Iguina#3]
Hi!

Looking at MonoGame Demo, whenever any new "window" (with some layout and auto-sizing combo) is first opened, it flickers for a frame - what I assume is the internal resizing based on layout. This is most obvious when (re)opening the popup message window, because it creates a new instance each time, so it has to resize it each time.

![before box](https://github.com/user-attachments/assets/157e9073-2e90-4d84-96b4-5475899157cd)

![box opening](https://github.com/user-attachments/assets/20ec77f2-9368-4109-b67c-a7e725cdc1c0)

![box opened](https://github.com/user-attachments/assets/ec7c2f35-0977-4108-babb-bd6c52b89e39)

If I check the `.Size` of the message box handle's `MessageBoxPanel`, then these are the values I see:

```
Frame #188
Before Draw: no message box
After Draw: no message box  // screenshot 1
// This is when I click the button to open the message box
Frame #189
Before Draw: X: 700 Pixels, Y: 600 Pixels
After Draw: X: 700 Pixels, Y: 1039 Pixels // screenshot 2
Frame #190
Before Draw: X: 700 Pixels, Y: 1039 Pixels
After Draw: X: 700 Pixels, Y: 414 Pixels // screenshot 3
// These values are now stable for the remainder of the box's lifetime
Frame #191
Before Draw: X: 700 Pixels, Y: 414 Pixels
After Draw: X: 700 Pixels, Y: 414 Pixels
```

P. S. I really like what I'm seeing with the project so far.

**Comment by RonenNess** [comment]
Thanks @RudyTheDev ,
I pushed a fix now that looks good with basic tests (fixes both message box and scrollbars).
If you want to try and compile latest to help with tests that would be nice :)
If not, you can just wait for next release.

Thanks!

**Comment by RudyTheDev** [comment]
Sure thing, I was working from the main anyway. 

That does indeed solve it for the first opening of the message box (and other entities). I was wondering how you fixed it so fast and I see that you do a dry (layout) run on the first entity addition.

But thinking broadly about what sort of things determine UI layout, this sort of flicker could be triggered by anything that affects entity visibility, positions or sizes. In other words, anything that makes the layout dirty.

I guess a simple way to show this is to add some text to the message box's label, so that the parent panel must autosize "around" it:

![before add text](https://github.com/user-attachments/assets/fe8e0812-ff93-4acf-a5f4-0a52a5aa1999)
![during add text](https://github.com/user-attachments/assets/8efae584-5cac-4b38-9479-fb7649123b1b)
![after add text](https://github.com/user-attachments/assets/e99a57c9-1a30-47c2-96ad-8d9023041017)

Since this isn't a new object, the dry run wouldn't get triggered.

Something else to consider is that even first entity creation layout changes can "propagate" along the hierarchy, so it's not necessarily enough to do 2 layout runs. For example, here [I create 15 panels in a hierarchy](https://github.com/RudyTheDev/Iguina/commit/c6a3eadc2b58e8ee48e846b1c31c3eb43cd18013#diff-e9ff92ddc0d3ffc9416001509251ae4990904fcb73eb119be143bed7c56bdbfeR337-R355), set the size for the smallest one and make all the other ones autosize:

![settle layout](https://github.com/user-attachments/assets/51630e90-0be3-41b5-93ee-49fdb059f37d)

**Comment by RonenNess** [comment]
Yeah it was a mistake to tie together rendering with layout placement. I should separate those flows some time, but that is very tricky with text entities that have dynamic size.

Do you have any suggestions?

PS here's a quick addition to your code to make the test easier:

```
newPanel.Events.OnClick = (Entity ent) =>
{
    ent.Size.Y.SetPixels(ent.Size.Y.Value == 200 ? 40 : 200);
};
```

**Comment by RudyTheDev** [comment]
> Do you have any suggestions?

I've been thinking about this a lot. I'm afraid I have no idea how to solve this elegantly.

As a background, I've been looking at all sorts of UI systems to use with MonoGame and UI layout approaches in general, so I don't have to write one myself. But I couldn't find a framework without some critical incompatibility or one that isn't way too complex for a "simple game GUI". So I have been writing a basic unfinished UI framework myself. I am actually doing things very similar to how you are. But layout issues is pretty much where I stopped before.

The way I am attempting to solve the principal layout problem with auto-sizing is having parents size either before or after the children depending on what determines the control's size. For example, if a child wants to be 80% of parent's fixed width, then parent sizes first. But if the parent wants to be 120% of the child's fixed width, then the child sizes first. As you can imagine, this requires a layout pass before a rendering pass, because layout calculation order is not going to be visually sequential.

Of course, in reality this gets complex fast. One has to determine all four X, Y, W and H values and each can depend on either parent's or children's or itself's one or more values. Which can in turn depend on further values. So whenever any value depends on another, I have to walk the "dependency chain" and resolve every value. If the UI is deterministic, then this seems to work fine. But this can also end up with circular dependencies, which have to be resolved gracefully.

Here's a simple example just to illustrate my thinking process and approach:

![box to label](https://github.com/user-attachments/assets/40a38664-8b25-4858-a6fd-8059d0b2e301)

I want to place the orange label horizontally in the middle of the blue box and resize the blue box to the height of its children (orange label). This is a somewhat simple anchoring and autosizing problem. Intuitively, you know exactly what "formulas" to use. But "encoding" this as value dependencies makes it really convoluted (but does illustrate how layout can be inter-dependent).

* Blue X and Y and W are known.
* Blue H depends on Orange H.
* Orange W and H are known.
* Orange Y depends on Blue Y
* Orange X depends on Blue X, W and Orange W.

Notably, these two "opposite chains" show that you cannot fully-place one or the other control first - you have to calculate values independently in a specific order:
* To calculate Orange X, you need to learn Blue X;
* To calculate Blue H, you need to learn Orange H.

Hope this leads you to some ideas about this. I'm just thinking aloud about the problem.
